# Targeting Azure Linux, but currently testing on Ubuntu, as ubuntu-slim doesn't
# support docker-in-docker.

name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'main')}}

permissions: read-all

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Setup"
        shell: bash
        run: |
          set -ex
          sudo --preserve-env=HOME ./scripts/setup-ubuntu.sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: "Run CI checks"
        shell: bash
        run: |
          set -ex
          cargo fmt -- --check
      
      - name: "Run tests"
        shell: bash
        run : |
          set -ex
          ./scripts/setup-openssl.sh
          cargo test
